# Интерфейс приложения 

In [ ]:
# -*- coding: utf-8 -*-
"""
Created on Mon Nov  1 11:40:37 2021

@author: Иван
"""
import tkinter as tk
import tkinter.filedialog as fd
import tkinter.messagebox as mb

class App(tk.Tk):
    '''
    Класс выбирает файл
    ''' 
    def __init__(self):
        super().__init__()
        btn_file = tk.Button(self, text="Выбрать файл",
                             command=self.choose_file)
      
        btn_file.pack(padx=120, pady=30)
        

    def choose_file(self):
        filetypes = (
                     ("Данные", "*.xls"),
                     )
        filename = fd.askopenfilename(title="Открыть файл", initialdir="/",
                                      filetypes=filetypes)
        if filename:
            print(filename)
            app.destroy()
class App2(tk.Tk):
    '''
    Сохранение файла
    ''' 
    def __init__(self):
        super().__init__()
       
        self.btn_save = tk.Button(self, text="Сохранить", command=self.save_file)

        self.btn_save.pack(pady=10, ipadx=5)

    def save_file(self):
        contents = "ааа"
        new_file = fd.asksaveasfile(title="Сохранить файл", defaultextension=".xls",
                                    filetypes=(("Результат", "*.xls"),))
        if new_file:
            new_file.write(contents)
            new_file.close() 
            app.destroy()
class App3(tk.Tk):
    '''
    Кнопка обработки
    '''
    def __init__(self):
        super().__init__()
        self.create_button(mb.askyesno, "Обработка",
                           "Вернет True или False")
        
    def create_button(self, dialog, title, message):
        command = lambda: print(dialog(title, message))
        btn = tk.Button(self, text=title, command=command)
        btn.pack(padx=40, pady=5, expand=True, fill=tk.BOTH)
if __name__ == "__main__":
    app = App()
    app.mainloop()
    app = App2()
    app.close()
    


TclError: ignored

# Обработка файлов

Иван Алексеевич

In [ ]:
import pandas as pd
import numpy as np
from statistics import mean

In [ ]:
data_train = '/content/Train.xlsx'
def load_train(data):
    '''
    data: Ссылка на тренировочный датасет
    '''
    data_train = pd.read_excel(data)
    data_train = data_train[1:data_train.size]
    numpy_dataset = []
    for j in range(1,len(data_train.columns)):
        numpy_dataset += [np.array(data_train[data_train.columns[j]])]
    for i in range(len(numpy_dataset)):
        for j in range(len(numpy_dataset[i])):
            if np.isnan(numpy_dataset[i][j]):
                numpy_dataset[i][j] = 0
    return numpy_dataset
data_train = load_train(data_train)


In [ ]:
def load_test(file):
    data = pd.read_excel(file)
    data_copy = data.copy()
    data_copy = data_copy.iloc[:, 1:]
    numpy_data = np.array(data_copy)
    
    for i in range(1, numpy_data.shape[1]):
        if(i == 1):
            Number_of_Forecast = np.count_nonzero(numpy_data[:, i] == 'Forecast')
        else:
            Number_of_Forecast = np.append(Number_of_Forecast, np.count_nonzero(numpy_data[:, i] == 'Forecast'))
    
    out = []
    for i in range(0, numpy_data.shape[1], 1):
        out.append(numpy_data[:, i][numpy_data[:, i] != 'Forecast'])
    
    if(len(set(Number_of_Forecast)) == 1):
        return out, "Безусловный прогноз"
    elif(np.count_nonzero(Number_of_Forecast == 0)):
        return out, "Условный прогноз"
    elif(any((i > mean(Number_of_Forecast)) for i in Number_of_Forecast)):
        return out, "Прогноз с задержкой статистики"
    else:
        return "error"

In [ ]:
load_test('/content/Test_example2.xlsx')

# From numpy to excel

In [ ]:
# Копирует не всю таблицу

data = pd.read_excel('/content/Test_example2.xlsx')
data_copy = data.copy()

dates = np.array(data_copy.tail(6)['Unnamed: 0'])
number_dates = len(dates)
dates = dates.reshape(number_dates, 1)

header = np.array(data_copy.columns)
number_header = len(header)
header = header.reshape(1, number_header)

data_copy = data_copy.iloc[:, 1:]

numpy_data = np.array(data_copy)
numpy_predict = numpy_data[2:8, :]
numpy_output = np.hstack((dates, numpy_predict))
numpy_output = np.vstack((header, numpy_output))

output_dataset = pd.DataFrame(numpy_output)
output_dataset.to_excel('/content/aboba.xlsx', index=False)
test = pd.read_excel('/content/aboba.xlsx')
test_copy = test.copy()
test

0         1      2         3         4
0  Unnamed: 0      Var1   Var2      Var3      Var4
1       10m07  0.026813  2.625  3.363693  0.061665
2       10m08  0.036764  1.888  3.130242  0.052624
3       10m09  0.044732  1.308  3.210488  0.042574
4       10m10    0.0527  1.361  3.240395  0.047561
5       10m11  0.059676  3.618  3.290428  0.074203
6       10m12  0.055668  3.813  3.366655  0.103762

In [ ]:
header = data_copy.columns
print(header)

Index(['Unnamed: 0', 'Var1', 'Var2', 'Var3', 'Var4'], dtype='object')


# Нэйросэть

In [ ]:
a = [f for f in a if f != 'Forecast']

In [ ]:
# demonstrate prediction
x_input = array([53.0, 60.0, 57.0,65.0])
x_input = x_input.reshape((1, n_seq, 1, n_steps, n_features))
yhat = model.predict(x_input, verbose=0)
print(yhat)

[[63.59119]]


In [ ]:
kolvo = 3
x_input = array([53.0, 60.0, 57.0,65.0])
for j in range(kolvo):
  x_pred = x_input.reshape((1, n_seq, 1, n_steps, n_features))
  c = list(x_input)
  yhat = model.predict(x_input, verbose=0)
  c.append(e)
  c.pop(0)
  x_input=array(c)

ValueError: ignored

In [ ]:
yhat = model.predict(x_input, verbose=0)

зависимость 

In [ ]:
val = numpy_data[1:120, 1]
import numpy as np
a = val
a =list(a)
a = [f for f in a if f != 'Forecast']
val2 = numpy_data[30:120, 2]
import numpy as np
a2 = val2
a2 =list(a2)
a2 = [f for f in a2 if f != 'Forecast']
val3 = numpy_data[1:120, 3]
import numpy as np
a3 = val3
a3 =list(a2)
a3 = [f for f in a3 if f != 'Forecast']

In [ ]:
# multivariate multi-step encoder-decoder lstm example
from numpy import array
from numpy import hstack
from keras.models import Sequential
from keras.layers import LSTM
from keras.layers import Dense
from keras.layers import RepeatVector
from keras.layers import TimeDistributed

# split a multivariate sequence into samples
def split_sequences(sequences, n_steps_in, n_steps_out):
	X, y = list(), list()
	for i in range(len(sequences)):
		# find the end of this pattern
		end_ix = i + n_steps_in
		out_end_ix = end_ix + n_steps_out
		# check if we are beyond the dataset
		if out_end_ix > len(sequences):
			break
		# gather input and output parts of the pattern
		seq_x, seq_y = sequences[i:end_ix, :], sequences[end_ix:out_end_ix, :]
		X.append(seq_x)
		y.append(seq_y)
	return array(X), array(y)

# define input sequence
in_seq1 = array(a)
in_seq2 = array(a2)
out_seq = array(a3)
# convert to [rows, columns] structure
in_seq1 = in_seq1.reshape((len(in_seq1), 1))
in_seq2 = in_seq2.reshape((len(in_seq2), 1))
out_seq = out_seq.reshape((len(out_seq), 1))
# horizontally stack columns
dataset = hstack((in_seq1, in_seq2, out_seq))
# choose a number of time steps
n_steps_in, n_steps_out = 4, 4
# covert into input/output
X, y = split_sequences(dataset, n_steps_in, n_steps_out)
# the dataset knows the number of features, e.g. 2
n_features = X.shape[2]
# define model
model = Sequential()
model.add(LSTM(200, activation='relu', input_shape=(n_steps_in, n_features)))
model.add(RepeatVector(n_steps_out))
model.add(LSTM(200, activation='relu', return_sequences=True))
model.add(TimeDistributed(Dense(n_features)))
model.compile(optimizer='adam', loss='mse')
# fit model
model.fit(X, y, epochs=300, verbose=0)


In [ ]:
# demonstrate prediction
t1= numpy_data[121:125, 1]
t2= numpy_data[121:125, 2]
t3= numpy_data[121:125, 3]
x_1 = [t1[0],t2[0],t3[0]]
x_2 = [t1[1],t2[1],t3[1]]
x_3 = [t1[2],t2[2],t3[2]]
x_4 = [t1[3],t2[3],t3[3]]
print(x_1,x_2,x_3,x_4)

[70.0, 89.0, 53.0] [73.0, 84.0, 56.0] [75.0, 88.0, 62.0] [63.0, 81.0, 71.0]


In [ ]:

x_input = array([x_1,x_2,x_3,x_4])
x_input = x_input.reshape((1, n_steps_in, n_features))
yhat = model.predict(x_input, verbose=0)
print(yhat)

[[[51.91063  75.498314 79.408035]
  [49.61627  78.1361   73.77707 ]
  [43.358624 75.09168  69.631836]
  [42.24751  71.53613  62.429417]]]


# Нейросеть на ежемесячные данные

In [ ]:
g = load_train('/content/Train.xlsx')
n = np.array(g)
b = []
for i in range(69):
  val = g[i][30:147]
  a =list(val)
  b.append(a)
c = []

for i in b:
  c.append(np.array(i))
for i in range(len(c)):
  c[i] = c[i].reshape((len(c[i]), 1))


<class 'float'>
69


# Многофакторная LSTM с кодером-декодером

In [ ]:
from numpy import array
from numpy import hstack
from keras.models import Sequential
from keras.layers import LSTM
from keras.layers import Dense
from keras.layers import RepeatVector
from keras.layers import TimeDistributed

# split a multivariate sequence into samples
def split_sequences(sequences, n_steps_in, n_steps_out):
	x, y = list(), list()
	for i in range(len(sequences)):
		# find the end of this pattern
		end_ix = i + n_steps_in
		out_end_ix = end_ix + n_steps_out
		# check if we are beyond the dataset
		if out_end_ix > len(sequences):
			break
		# gather input and output parts of the pattern
		seq_x, seq_y = sequences[i:end_ix, :], sequences[end_ix:out_end_ix, :]
		x.append(seq_x)
		y.append(seq_y)
	return array(X), array(y)



# horizontally stack columns
dataset = hstack(c)
# choose a number of time steps
n_steps_in, n_steps_out = 10, 5
# covert into input/output
X, y = split_sequences(dataset, n_steps_in, n_steps_out)
# the dataset knows the number of features, e.g. 2
n_features = X.shape[2]


In [ ]:
model = Sequential()
model.add(LSTM(200, activation='relu', input_shape=(n_steps_in, n_features)))
model.add(RepeatVector(n_steps_out))
model.add(LSTM(200, activation='relu', return_sequences=True))
model.add(TimeDistributed(Dense(n_features)))
model.compile(optimizer='adam', loss='mse')

In [ ]:
model.fit(X, y, epochs=500, verbose=0)

In [ ]:
#заргузка из датасета
numpy_data = load_train('/content/Train.xlsx')
b =[]
# c = []
for i in range(69):
  val = numpy_data[i][137:147]
  a =list(val)
  b.append(a)
c = []
# define input sequence
for i in b:
  c.append(np.array(i))


In [ ]:
c

[array([63., 63., 58., 63., 67., 63., 66., 81., 78., 85.]),
 array([84., 84., 79., 80., 83., 77., 87., 92., 95., 91.]),
 array([61., 62., 63., 63., 54., 57., 49., 48., 49., 57.]),
 array([45., 42., 41., 38., 40., 45., 40., 38., 36., 38.]),
 array([63., 55., 55., 56., 48., 45., 45., 31., 32., 38.]),
 array([34., 36., 32., 34., 36., 42., 27., 30., 22., 30.]),
 array([58., 56., 55., 61., 51., 57., 50., 36., 38., 40.]),
 array([60., 61., 58., 62., 56., 52., 45., 41., 42., 45.]),
 array([16., 30., 24., 26., 23., 19., 24., 26., 28., 24.]),
 array([6.80682936, 6.84374995, 6.85012617, 7.00760061, 7.12125245,
        7.25911613, 7.38770924, 6.85329909, 6.85646198, 6.93731408]),
 array([8.10440131, 8.0836372 , 8.00636757, 7.8860814 , 7.74283596,
        7.60688453, 7.62510715, 7.51806418, 7.55538194, 7.72753511]),
 array([8.25452888, 8.25035895, 8.23270601, 8.15679705, 8.14612951,
        8.06746267, 8.1131271 , 8.13211877, 8.00936308, 8.14931284]),
 array([6.02053779, 6.02053779, 6.01956598, 6.

In [ ]:
x_input = array(c)
x_input = x_input.reshape((1, n_steps_in, n_features))

In [ ]:
yhat = model.predict(x_input, verbose=0)

In [ ]:
from math import exp
from statistics import variance as var
from random import random
data_1 = [[j for j in range(24)] for i in range(5)]
data_2 = [[j + 1 + random() for j in range(24)] for i in range(5)]

def scoring(real_data, predicted_data, n):
    '''
    real_data: фактические значения
    predicted_data: предсказанные
    n: сколько предсказывали
    '''
    x = [real_data[i][-n:] for i in range(len(real_data))]
    x_hat = [predicted_data[i][-n:] for i in range(len(predicted_data))]
    M = len(real_data)
    # M = real_data.shape[0]
    alpha = 12
    # Количество точек для прогнозирования
    Km = [sum(x[i]) for i in range(len(x))]

    Nm = len(real_data)
    # Горизонт прогнозирования
    Hm = n
    
    Dm = [var([predicted_data[j][i] - predicted_data[j][i-12] for i in range(len(predicted_data[j]) - n, len(predicted_data[j]))]) for j in range(len(predicted_data))]

    WMSFEm = [1 / Km[k] * (sum([sum([(x[i][h] - x_hat[i][h])**2 / (h*Dm[i]) for h in range(1,Hm)]) for i in range(Nm)])) for k in range(len(Km))]
    Score = 1 / M * sum(WMSFEm)
    return Score



In [ ]:
#заргузка из датасета
b =[]
numpy_data = load_train('/content/Train.xlsx')
for i in range(69):
  val = numpy_data[i][30:152]
  a =list(val)
  b.append(a)
real_data = []
# define input sequence
for i in b:
  real_data.append(array(i))

In [ ]:
#заргузка из датасета
b =[]
predicted_data = []
for i in range(69):
  val = numpy_data[30:147, i+1]
  a =list(val)
  b.append(a)
predicted_data = []
# define input sequence
for i in b:
  predicted_data.append(array(i))

# Решающий лес

In [ ]:
# Регрессионный анализ и поиск, к какому столбцу тренировочного множества
# наиболее вероятно относится столбец в тестовом, с помощью
# коэффициента детерминации

from scipy import stats


def get_column(base, array):
    determination = {}
    for i, k in enumerate(array):
        for j, n in enumerate(base):
            if len(k) != len(n):
                n = n[:len(k)]
            n, k = np.array(n), np.array(k)
            
            slope, intercept, r, p, se = stats.linregress(n.astype(float), k.astype(float))
            determination[(i, j)] = r ** 2
    what_column = []
    for i in range(len(array)):
        new_det = [determination[(i, j)] for j in range(len(base))]
        what_column.append([i, new_det.index(max(new_det))])
    return what_column


base = load_train('/content/Train.xlsx')
test, marker = load_test('/content/Test_example2.xlsx')
columns = get_column(base, test)

[[0, 36], [1, 61], [2, 68], [3, 27]]


In [189]:
import scipy as sp
from sklearn.ensemble import RandomForestRegressor


def check_crosscorr(array):
    
    array = [array[:min([len(i) for i in array])] for j in range(len(array))]
    # print(array)
    pearson_corr = []
    pearson_p = [[0 for i in range(len(array))] for i in range(len(array))]
    spearman_p = [[0 for i in range(len(array))] for i in range(len(array))]
    for i, n in enumerate(array):
        for j, k in enumerate(array):
            print(type(n))
            pearson_p[i][j] = sp.stats.pearsonr(n, k)[1]
            spearman_p[i][j] = sp.stats.spearmanr(n, k)[1]
    correlated_p = []
    correlated_s = []
    for i in range(len(pearson_p)):
        for j in range(len(pearson_p[i])):
            if pearson_p[i][j] < 0.05 and i != j:
                if [j, i] not in correlated_p:
                    correlated_p.append([i, j])
    for i in range(len(spearman_p)):
        for j in range(len(spearman_p[i])):
            if spearman_p[i][j] < 0.05 and i != j:
                if [j, i] not in correlated_s:
                    correlated_s.append([i, j])

    return correlated_p


def mlmodels(table):
    
    model = RandomForestRegressor(n_estimators=100)
    
    prework = {}
    crosscorr = check_crosscorr(table)
    
    for i, k in enumerate(table):
        prework[i] = []
        for j in crosscorr:
            if i in j:
                prework[i].append(j[:].pop(j.index(i)-1))
    print(prework)
    # no_multicor = {}
    # for i in range(len(prework)):
    #     if len(prework[i]) <= 1: no_multicor[i] = prework[i][:]
    #     else:
    #         no_multicor[i] = []
    #         for j in prework[i]:
    #             # print(prework[i])
    #             temp = prework[i][:]
    #             temp.remove(j)

    #             for k in temp:
    #                 if j not in prework[k] and j not in no_multicor[i]:
    #                     no_multicor[i].append(j)
    #         if not no_multicor[i]:
    #             no_multicor[i].append(prework[i][-1])
    # for i in range(len(no_multicor)):
    #     if not no_multicor[i]:
    #         models.append([])
    #     else:
    #         xtrain = np.array([table[j] for j in no_multicor[i]])
    #         xtrain = xtrain.reshape((xtrain.shape[1], xtrain.shape[0]))
    #         ytrain = np.array(table[i])
    #         models.append(model.fit(xtrain, ytrain))
    # return models, no_multicor


mlmodels(test)

<class 'list'>


AttributeError: ignored

In [178]:
# Делаем таблицу с тестовыми элементами, соответствующей начальной таблице
zero_base = [[0 for j in range(len(base[0]))] for i in range(len(base))]
columns = get_column(base, test)
known_columns = [i[1] for i in columns]
# Подставляем известные значения из теста в эту таблицу
lengths = []
for i in columns:
    zero_base[i[1]][:len(test[i[0]])] = test[i[0]]
    # zero_base[i[1]][len(test[i[0]]):] = [0 for j in range(len(base[i[1]]) - len(test[i[0]]))]
    lengths.append(len(test[i[0]]))
# Пока длина всех известных столбцов неравна, то запускаем решающий лес для
# дозаполнения до нужной длины, иначе - применяем нейросеть
# 
print(len(correlated[known_columns[0]]))
for i in known_columns:
    current = [zero_base[i][j] for j in range(len(zero_base[i])) if zero_base[i][j] != 0]
    while len(current) != max(lengths):
        xtrain = [zero_base[k][len(current) + 1] for k in correlated[i]] 
        xtrain = np.array(xtrain).reshape((1, -1))
        print(xtrain)
        zero_base[i][len(current) + 1] = models[i].predict(xtrain)
        current = [zero_base[i][j] for j in range(len(zero_base[i])) if zero_base[i][j] != 0 and j != 0]

print(zero_base)

15
[[0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         4.69866053]]


ValueError: ignored